/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedBackupRestoreRouteImport } from './routes/_authenticated/backup-restore'
import { Route as AuthenticatedCalculatorRouteImport } from './routes/_authenticated/calculator'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDailyReportRouteImport } from './routes/_authenticated/daily-report'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMusicManagerRouteImport } from './routes/_authenticated/music-manager'
import { Route as AuthenticatedNewOrderRouteImport } from './routes/_authenticated/new-order'
import { Route as AuthenticatedOrderHistoryRouteImport } from './routes/_authenticated/order-history'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProductManagerRouteImport } from './routes/_authenticated/product-manager'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedReportTrackerRouteImport } from './routes/_authenticated/report-tracker'
import { Route as AuthenticatedTrackOrdersRouteImport } from './routes/_authenticated/track-orders'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBackupRestoreRoute =
  AuthenticatedBackupRestoreRouteImport.update({
    id: '/backup-restore',
    path: '/backup-restore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalculatorRoute = AuthenticatedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyReportRoute =
  AuthenticatedDailyReportRouteImport.update({
    id: '/daily-report',
    path: '/daily-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicManagerRoute =
  AuthenticatedMusicManagerRouteImport.update({
    id: '/music-manager',
    path: '/music-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewOrderRoute = AuthenticatedNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrderHistoryRoute =
  AuthenticatedOrderHistoryRouteImport.update({
    id: '/order-history',
    path: '/order-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductManagerRoute =
  AuthenticatedProductManagerRouteImport.update({
    id: '/product-manager',
    path: '/product-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportTrackerRoute =
  AuthenticatedReportTrackerRouteImport.update({
    id: '/report-tracker',
    path: '/report-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackOrdersRoute =
  AuthenticatedTrackOrdersRouteImport.update({
    id: '/track-orders',
    path: '/track-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/music-manager': typeof AuthenticatedMusicManagerRoute
  '/new-order': typeof AuthenticatedNewOrderRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/product-manager': typeof AuthenticatedProductManagerRoute
  '/products': typeof AuthenticatedProductsRoute
  '/report-tracker': typeof AuthenticatedReportTrackerRoute
  '/track-orders': typeof AuthenticatedTrackOrdersRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/music-manager': typeof AuthenticatedMusicManagerRoute
  '/new-order': typeof AuthenticatedNewOrderRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/product-manager': typeof AuthenticatedProductManagerRoute
  '/products': typeof AuthenticatedProductsRoute
  '/report-tracker': typeof AuthenticatedReportTrackerRoute
  '/track-orders': typeof AuthenticatedTrackOrdersRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/backup-restore': typeof AuthenticatedBackupRestoreRoute
  '/_authenticated/calculator': typeof AuthenticatedCalculatorRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/daily-report': typeof AuthenticatedDailyReportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/music-manager': typeof AuthenticatedMusicManagerRoute
  '/_authenticated/new-order': typeof AuthenticatedNewOrderRoute
  '/_authenticated/order-history': typeof AuthenticatedOrderHistoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/product-manager': typeof AuthenticatedProductManagerRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/report-tracker': typeof AuthenticatedReportTrackerRoute
  '/_authenticated/track-orders': typeof AuthenticatedTrackOrdersRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/activity-log'
    | '/backup-restore'
    | '/calculator'
    | '/customers'
    | '/daily-report'
    | '/dashboard'
    | '/music-manager'
    | '/new-order'
    | '/order-history'
    | '/orders'
    | '/product-manager'
    | '/products'
    | '/report-tracker'
    | '/track-orders'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/activity-log'
    | '/backup-restore'
    | '/calculator'
    | '/customers'
    | '/daily-report'
    | '/dashboard'
    | '/music-manager'
    | '/new-order'
    | '/order-history'
    | '/orders'
    | '/product-manager'
    | '/products'
    | '/report-tracker'
    | '/track-orders'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/activities'
    | '/_authenticated/activity-log'
    | '/_authenticated/backup-restore'
    | '/_authenticated/calculator'
    | '/_authenticated/customers'
    | '/_authenticated/daily-report'
    | '/_authenticated/dashboard'
    | '/_authenticated/music-manager'
    | '/_authenticated/new-order'
    | '/_authenticated/order-history'
    | '/_authenticated/orders'
    | '/_authenticated/product-manager'
    | '/_authenticated/products'
    | '/_authenticated/report-tracker'
    | '/_authenticated/track-orders'
    | '/_authenticated/user-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup-restore': {
      id: '/_authenticated/backup-restore'
      path: '/backup-restore'
      fullPath: '/backup-restore'
      preLoaderRoute: typeof AuthenticatedBackupRestoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculator': {
      id: '/_authenticated/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthenticatedCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-report': {
      id: '/_authenticated/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AuthenticatedDailyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music-manager': {
      id: '/_authenticated/music-manager'
      path: '/music-manager'
      fullPath: '/music-manager'
      preLoaderRoute: typeof AuthenticatedMusicManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-order': {
      id: '/_authenticated/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof AuthenticatedNewOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-history': {
      id: '/_authenticated/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof AuthenticatedOrderHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-manager': {
      id: '/_authenticated/product-manager'
      path: '/product-manager'
      fullPath: '/product-manager'
      preLoaderRoute: typeof AuthenticatedProductManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-tracker': {
      id: '/_authenticated/report-tracker'
      path: '/report-tracker'
      fullPath: '/report-tracker'
      preLoaderRoute: typeof AuthenticatedReportTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/track-orders': {
      id: '/_authenticated/track-orders'
      path: '/track-orders'
      fullPath: '/track-orders'
      preLoaderRoute: typeof AuthenticatedTrackOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedBackupRestoreRoute: typeof AuthenticatedBackupRestoreRoute
  AuthenticatedCalculatorRoute: typeof AuthenticatedCalculatorRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDailyReportRoute: typeof AuthenticatedDailyReportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMusicManagerRoute: typeof AuthenticatedMusicManagerRoute
  AuthenticatedNewOrderRoute: typeof AuthenticatedNewOrderRoute
  AuthenticatedOrderHistoryRoute: typeof AuthenticatedOrderHistoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductManagerRoute: typeof AuthenticatedProductManagerRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportTrackerRoute: typeof AuthenticatedReportTrackerRoute
  AuthenticatedTrackOrdersRoute: typeof AuthenticatedTrackOrdersRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedBackupRestoreRoute: AuthenticatedBackupRestoreRoute,
  AuthenticatedCalculatorRoute: AuthenticatedCalculatorRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDailyReportRoute: AuthenticatedDailyReportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMusicManagerRoute: AuthenticatedMusicManagerRoute,
  AuthenticatedNewOrderRoute: AuthenticatedNewOrderRoute,
  AuthenticatedOrderHistoryRoute: AuthenticatedOrderHistoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductManagerRoute: AuthenticatedProductManagerRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportTrackerRoute: AuthenticatedReportTrackerRoute,
  AuthenticatedTrackOrdersRoute: AuthenticatedTrackOrdersRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
